### ISSUE TITLE
Idea: CRYSTALS (Dilithium)

### ISSUE THREAD

**Issue by neil-yoga-crypto** [cyph/pqcrypto.js#1]
Since NIST proposed CRYSTALS to be standardized (https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/G0DoD7lkGPk), both for signatures (Dilithium) and Encryption (KYBER) it would be highly appreciated, atleast by me, if they would be supported in your post-quantum crypto library!

Thank you for everything you're doing!

**Comment by buu700** [comment]
Done, and happy to help!
