### ISSUE TITLE
ntru is useless: no parameter for data to encrypt

### ISSUE THREAD

**Issue by amytimed** [cyph/pqcrypto.js#11]
im stuck on ntru-legacy because of that :/

```js
await ntru.encrypt(keyPair.publicKey)
```

this only takes a public key

in ntru-legacy we can pass a uint8array

**Comment by StringManolo** [comment]
> im stuck on ntru-legacy because of that :/
> 
> ```js
> await ntru.encrypt(keyPair.publicKey)
> ```
> 
> this only takes a public key
> 
> in ntru-legacy we can pass a uint8array

I was going to fix it but the repo dosn't have license and seems not active at all neither has a CONTRIBUTION.md

Instead you can use [node-pqclean](https://github.com/tniessen/node-pqclean)

[Here](https://github.com/StringManolo/DarkMessengerCrypto/blob/6d6f63d53c49ae9505c85efa9c70255879f649e3/crypto_modules/KYBER_module.js) you have a module i made for 1 way comunications. (In Dual channel you have to preshare the key in the tunnel. I include the pub key directly in the encryption output cuz i only need 1 way communications and temporal keys for the emisor)

**Comment by buu700** [comment]
Hey, really sorry about the late reply on this! Just to clarify, this is as intended. The algorithms are provided with a KEM interface, which returns a symmetric key that can be used by each party to encrypt and decrypt.

This aligns with how the legacy ntru package had advised using it, but is slightly simpler/higher-level and prevents misuse. It's also consistent with the interfaces exposed by the reference implementations of the algorithms that came out of NIST PQC.

~License files are included in the individual package folders.~ Edit: Whoops, actually it is included in the root of the project. It's just called "LICENSE".
